package trkit

import (
	"errors"
	"fmt"
	"testing"
)

// validIBAN is the IBAN used throughout these tests: 26 characters, a zero in
// the reserved position, and a checksum that satisfies mod-97. It is a
// documentation example, not anyone's account.
const validIBAN = "TR330006100519786457841326"

// These strings satisfy mod-97 but are not valid Turkish IBANs. They exist to
// prove that the checksum alone cannot carry the validation: the first two are
// TR-prefixed and the wrong length, the third is a well-formed IBAN from
// another country. Each was generated by computing genuine ISO 13616 check
// digits for a BBAN of the wrong size.
const (
	shortIBANPassingMod97   = "TR2511111111111111111111"     // 24 characters
	longIBANPassingMod97    = "TR19111111111111111111111111" // 28 characters
	foreignIBANPassingMod97 = "DE89370400440532013000"       // valid, but German
)

func TestCleanIBAN(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"grouped in fours", "TR33 0006 1005 1978 6457 8413 26", validIBAN},
		{"already compact", validIBAN, validIBAN},
		{"lowercase", "tr330006100519786457841326", validIBAN},
		{"mixed case and spaces", "tr33 0006 1005 1978 6457 8413 26", validIBAN},
		{"surrounding spaces", "  " + validIBAN + "  ", validIBAN},
		{"irregular spacing", "TR33000  61005 19786457841326", validIBAN},
		{"empty", "", ""},

		// Hyphens survive cleaning on purpose, so that the structure check
		// rejects them instead of the cleaner quietly accepting them.
		{"hyphenated", "TR33-0006-1005", "TR33-0006-1005"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := cleanIBAN(tt.input); got != tt.want {
				t.Errorf("cleanIBAN(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestHasIBANStructure(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  bool
	}{
		{"valid", validIBAN, true},

		// Structure and checksum are separate concerns: a number may be shaped
		// correctly and still fail mod-97, which this function does not check.
		{"wrong check digits but right shape", "TR340006100519786457841326", true},

		{"empty", "", false},
		{"one character short", validIBAN[:25], false},
		{"one character long", validIBAN + "7", false},
		{"foreign country code", "DE330006100519786457841326", false},
		{"lowercase country code", "tr330006100519786457841326", false},
		{"letter among the digits", "TR33000610051978645784132X", false},
		{"reserved digit not zero", "TR330006110519786457841326", false},
		// Exactly 26 characters, so this fails on the digit check rather than
		// on length — which is the point of the case.
		{"hyphen where a digit belongs", "TR33-006100519786457841326", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := hasIBANStructure(tt.input); got != tt.want {
				t.Errorf("hasIBANStructure(%q) = %v, want %v", tt.input, got, tt.want)
			}
		})
	}
}

func TestIBANChecksumOK(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  bool
	}{
		{"valid", validIBAN, true},
		{"wrong check digits", "TR340006100519786457841326", false},
		{"empty", "", false},
		{"invalid character", "TR33000610051978645784132!", false},

		// The checksum is length-agnostic, so these come out true. Only the
		// structural check rejects them; see TestIsValidIBANNeedsBothChecks.
		{"too short but checksum-clean", shortIBANPassingMod97, true},
		{"too long but checksum-clean", longIBANPassingMod97, true},
		{"foreign but checksum-clean", foreignIBANPassingMod97, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := ibanChecksumOK(tt.input); got != tt.want {
				t.Errorf("ibanChecksumOK(%q) = %v, want %v", tt.input, got, tt.want)
			}
		})
	}
}

func TestIsValidIBAN(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  bool
	}{
		{"compact", validIBAN, true},
		{"grouped in fours", "TR33 0006 1005 1978 6457 8413 26", true},
		{"lowercase", "tr330006100519786457841326", true},
		{"mixed case and spaces", "tr33 0006 1005 1978 6457 8413 26", true},
		{"surrounding spaces", "  " + validIBAN + "  ", true},

		{"empty", "", false},
		{"one character short", validIBAN[:25], false},
		{"one character long", validIBAN + "7", false},
		{"wrong check digits", "TR340006100519786457841326", false},
		{"reserved digit not zero", "TR330006110519786457841326", false},
		{"hyphen where a digit belongs", "TR33-006100519786457841326", false},
		{"letter among the digits", "TR33000610051978645784132X", false},
		{"digits only, no country code", "33000610051978645784132600", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := IsValidIBAN(tt.input); got != tt.want {
				t.Errorf("IsValidIBAN(%q) = %v, want %v", tt.input, got, tt.want)
			}
		})
	}
}

// Neither check is sufficient on its own, and this is the case that proves it:
// every input below satisfies mod-97, so an implementation that trusted the
// checksum would accept all three. Structure is what rejects them.
func TestIsValidIBANNeedsBothChecks(t *testing.T) {
	for _, iban := range []string{
		shortIBANPassingMod97,
		longIBANPassingMod97,
		foreignIBANPassingMod97,
	} {
		if !ibanChecksumOK(iban) {
			t.Fatalf("test setup is wrong: %q should satisfy mod-97", iban)
		}
		if IsValidIBAN(iban) {
			t.Errorf("IsValidIBAN(%q) = true, want false: mod-97 passes but the structure is wrong", iban)
		}
	}
}

func TestNormalizeIBAN(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"grouped in fours", "TR33 0006 1005 1978 6457 8413 26", validIBAN},
		{"already compact", validIBAN, validIBAN},
		{"lowercase", "tr330006100519786457841326", validIBAN},
		{"mixed case and spaces", "tr33 0006 1005 1978 6457 8413 26", validIBAN},
		{"surrounding spaces", "  " + validIBAN + "  ", validIBAN},
		{"irregular spacing", "TR33000  61005 19786457841326", validIBAN},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := NormalizeIBAN(tt.input)
			if err != nil {
				t.Fatalf("NormalizeIBAN(%q) returned error %v, want none", tt.input, err)
			}
			if got != tt.want {
				t.Errorf("NormalizeIBAN(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestNormalizeIBANRejects(t *testing.T) {
	tests := []struct {
		name  string
		input string
	}{
		{"empty", ""},
		{"one character short", validIBAN[:25]},
		{"one character long", validIBAN + "7"},
		{"wrong check digits", "TR340006100519786457841326"},
		{"reserved digit not zero", "TR330006110519786457841326"},
		{"hyphen where a digit belongs", "TR33-006100519786457841326"},
		{"too short but checksum-clean", shortIBANPassingMod97},
		{"too long but checksum-clean", longIBANPassingMod97},
		{"foreign but checksum-clean", foreignIBANPassingMod97},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := NormalizeIBAN(tt.input)
			if !errors.Is(err, ErrInvalidIBAN) {
				t.Errorf("NormalizeIBAN(%q) error = %v, want %v", tt.input, err, ErrInvalidIBAN)
			}
			if got != "" {
				t.Errorf("NormalizeIBAN(%q) = %q, want empty string on failure", tt.input, got)
			}
		})
	}
}

// Normalizing an already-normalized IBAN must return it unchanged, so that
// callers can apply the function to values of unknown provenance without
// worrying whether it has run before.
func TestNormalizeIBANIsIdempotent(t *testing.T) {
	inputs := []string{
		validIBAN,
		"TR33 0006 1005 1978 6457 8413 26",
		"tr330006100519786457841326",
		"  " + validIBAN + "  ",
	}

	for _, input := range inputs {
		once, err := NormalizeIBAN(input)
		if err != nil {
			t.Fatalf("NormalizeIBAN(%q) returned error %v, want none", input, err)
		}

		twice, err := NormalizeIBAN(once)
		if err != nil {
			t.Fatalf("NormalizeIBAN(%q) returned error %v on second pass, want none", once, err)
		}
		if twice != once {
			t.Errorf("NormalizeIBAN is not idempotent for %q: %q then %q", input, once, twice)
		}
	}
}

// IsValidIBAN and NormalizeIBAN must agree on every input, since one is defined
// in terms of the other. This pins that relationship so a later change to
// either cannot quietly split them.
func TestIsValidIBANAgreesWithNormalize(t *testing.T) {
	inputs := []string{
		validIBAN,
		"TR33 0006 1005 1978 6457 8413 26",
		"tr330006100519786457841326",
		"",
		validIBAN[:25],
		"TR340006100519786457841326",
		shortIBANPassingMod97,
		longIBANPassingMod97,
		foreignIBANPassingMod97,
	}

	for _, input := range inputs {
		_, err := NormalizeIBAN(input)
		if got, want := IsValidIBAN(input), err == nil; got != want {
			t.Errorf("IsValidIBAN(%q) = %v, but NormalizeIBAN error = %v", input, got, err)
		}
	}
}

// formattedIBAN is validIBAN in display form: six groups of four and a final
// group of two.
const formattedIBAN = "TR33 0006 1005 1978 6457 8413 26"

func TestFormatIBAN(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"compact", validIBAN, formattedIBAN},
		{"already formatted", formattedIBAN, formattedIBAN},
		{"lowercase", "tr330006100519786457841326", formattedIBAN},
		{"irregular spacing", "TR33000  61005 19786457841326", formattedIBAN},
		{"surrounding spaces", "  " + validIBAN + "  ", formattedIBAN},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := FormatIBAN(tt.input)
			if err != nil {
				t.Fatalf("FormatIBAN(%q) returned error %v, want none", tt.input, err)
			}
			if got != tt.want {
				t.Errorf("FormatIBAN(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestFormatIBANRejects(t *testing.T) {
	tests := []struct {
		name  string
		input string
	}{
		{"empty", ""},
		{"one character short", validIBAN[:25]},
		{"wrong check digits", "TR340006100519786457841326"},
		{"reserved digit not zero", "TR330006110519786457841326"},
		{"too short but checksum-clean", shortIBANPassingMod97},
		{"foreign but checksum-clean", foreignIBANPassingMod97},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := FormatIBAN(tt.input)
			if !errors.Is(err, ErrInvalidIBAN) {
				t.Errorf("FormatIBAN(%q) error = %v, want %v", tt.input, err, ErrInvalidIBAN)
			}
			if got != "" {
				t.Errorf("FormatIBAN(%q) = %q, want empty string on failure", tt.input, got)
			}
		})
	}
}

// The two representations must convert back and forth without loss: a formatted
// IBAN normalizes to the compact form it came from.
func TestFormatIBANRoundTrips(t *testing.T) {
	formatted, err := FormatIBAN(validIBAN)
	if err != nil {
		t.Fatalf("FormatIBAN(%q) returned error %v, want none", validIBAN, err)
	}

	back, err := NormalizeIBAN(formatted)
	if err != nil {
		t.Fatalf("NormalizeIBAN(%q) returned error %v, want none", formatted, err)
	}
	if back != validIBAN {
		t.Errorf("round trip gave %q, want %q", back, validIBAN)
	}

	// Formatting is idempotent for the same reason: it normalizes first.
	twice, err := FormatIBAN(formatted)
	if err != nil {
		t.Fatalf("FormatIBAN(%q) returned error %v, want none", formatted, err)
	}
	if twice != formatted {
		t.Errorf("FormatIBAN is not idempotent: %q then %q", formatted, twice)
	}
}

// The grouping is fixed, so the display form has a fixed width: 26 characters
// plus six separators.
func TestFormatIBANWidth(t *testing.T) {
	formatted, err := FormatIBAN(validIBAN)
	if err != nil {
		t.Fatalf("FormatIBAN(%q) returned error %v, want none", validIBAN, err)
	}

	const want = ibanLength + (ibanLength-1)/ibanGroupSize
	if len(formatted) != want {
		t.Errorf("len(%q) = %d, want %d", formatted, len(formatted), want)
	}
}

func ExampleIsValidIBAN() {
	fmt.Println(IsValidIBAN("TR33 0006 1005 1978 6457 8413 26"))
	fmt.Println(IsValidIBAN("tr330006100519786457841326"))

	// A valid IBAN, but not a Turkish one.
	fmt.Println(IsValidIBAN("DE89370400440532013000"))
	// Output:
	// true
	// true
	// false
}

func ExampleNormalizeIBAN() {
	// However it is written, one number gives one canonical string to store.
	for _, written := range []string{
		"TR33 0006 1005 1978 6457 8413 26",
		"tr330006100519786457841326",
		"  TR330006100519786457841326  ",
	} {
		iban, err := NormalizeIBAN(written)
		if err != nil {
			fmt.Println("error:", err)
			continue
		}
		fmt.Println(iban)
	}
	// Output:
	// TR330006100519786457841326
	// TR330006100519786457841326
	// TR330006100519786457841326
}

func ExampleFormatIBAN() {
	pretty, err := FormatIBAN("TR330006100519786457841326")
	if err != nil {
		fmt.Println("error:", err)
		return
	}
	fmt.Println(pretty)
	// Output: TR33 0006 1005 1978 6457 8413 26
}

func ExampleNormalizeIBAN_invalid() {
	_, err := NormalizeIBAN("TR00 1234")
	fmt.Println(errors.Is(err, ErrInvalidIBAN))
	// Output: true
}
