package trkit

import "testing"

// validIBAN is the IBAN used throughout these tests: 26 characters, a zero in
// the reserved position, and a checksum that satisfies mod-97. It is a
// documentation example, not anyone's account.
const validIBAN = "TR330006100519786457841326"

// These strings satisfy mod-97 but are not valid Turkish IBANs. They exist to
// prove that the checksum alone cannot carry the validation: the first two are
// TR-prefixed and the wrong length, the third is a well-formed IBAN from
// another country. Each was generated by computing genuine ISO 13616 check
// digits for a BBAN of the wrong size.
const (
	shortIBANPassingMod97   = "TR2511111111111111111111"     // 24 characters
	longIBANPassingMod97    = "TR19111111111111111111111111" // 28 characters
	foreignIBANPassingMod97 = "DE89370400440532013000"       // valid, but German
)

func TestCleanIBAN(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"grouped in fours", "TR33 0006 1005 1978 6457 8413 26", validIBAN},
		{"already compact", validIBAN, validIBAN},
		{"lowercase", "tr330006100519786457841326", validIBAN},
		{"mixed case and spaces", "tr33 0006 1005 1978 6457 8413 26", validIBAN},
		{"surrounding spaces", "  " + validIBAN + "  ", validIBAN},
		{"irregular spacing", "TR33000  61005 19786457841326", validIBAN},
		{"empty", "", ""},

		// Hyphens survive cleaning on purpose, so that the structure check
		// rejects them instead of the cleaner quietly accepting them.
		{"hyphenated", "TR33-0006-1005", "TR33-0006-1005"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := cleanIBAN(tt.input); got != tt.want {
				t.Errorf("cleanIBAN(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestHasIBANStructure(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  bool
	}{
		{"valid", validIBAN, true},

		// Structure and checksum are separate concerns: a number may be shaped
		// correctly and still fail mod-97, which this function does not check.
		{"wrong check digits but right shape", "TR340006100519786457841326", true},

		{"empty", "", false},
		{"one character short", validIBAN[:25], false},
		{"one character long", validIBAN + "7", false},
		{"foreign country code", "DE330006100519786457841326", false},
		{"lowercase country code", "tr330006100519786457841326", false},
		{"letter among the digits", "TR33000610051978645784132X", false},
		{"reserved digit not zero", "TR330006110519786457841326", false},
		// Exactly 26 characters, so this fails on the digit check rather than
		// on length — which is the point of the case.
		{"hyphen where a digit belongs", "TR33-006100519786457841326", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := hasIBANStructure(tt.input); got != tt.want {
				t.Errorf("hasIBANStructure(%q) = %v, want %v", tt.input, got, tt.want)
			}
		})
	}
}

func TestIBANChecksumOK(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  bool
	}{
		{"valid", validIBAN, true},
		{"wrong check digits", "TR340006100519786457841326", false},
		{"empty", "", false},
		{"invalid character", "TR33000610051978645784132!", false},

		// The checksum is length-agnostic, so these come out true. Only the
		// structural check rejects them; see TestIsValidIBANNeedsBothChecks.
		{"too short but checksum-clean", shortIBANPassingMod97, true},
		{"too long but checksum-clean", longIBANPassingMod97, true},
		{"foreign but checksum-clean", foreignIBANPassingMod97, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := ibanChecksumOK(tt.input); got != tt.want {
				t.Errorf("ibanChecksumOK(%q) = %v, want %v", tt.input, got, tt.want)
			}
		})
	}
}

func TestIsValidIBAN(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  bool
	}{
		{"compact", validIBAN, true},
		{"grouped in fours", "TR33 0006 1005 1978 6457 8413 26", true},
		{"lowercase", "tr330006100519786457841326", true},
		{"mixed case and spaces", "tr33 0006 1005 1978 6457 8413 26", true},
		{"surrounding spaces", "  " + validIBAN + "  ", true},

		{"empty", "", false},
		{"one character short", validIBAN[:25], false},
		{"one character long", validIBAN + "7", false},
		{"wrong check digits", "TR340006100519786457841326", false},
		{"reserved digit not zero", "TR330006110519786457841326", false},
		{"hyphen where a digit belongs", "TR33-006100519786457841326", false},
		{"letter among the digits", "TR33000610051978645784132X", false},
		{"digits only, no country code", "33000610051978645784132600", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := IsValidIBAN(tt.input); got != tt.want {
				t.Errorf("IsValidIBAN(%q) = %v, want %v", tt.input, got, tt.want)
			}
		})
	}
}

// Neither check is sufficient on its own, and this is the case that proves it:
// every input below satisfies mod-97, so an implementation that trusted the
// checksum would accept all three. Structure is what rejects them.
func TestIsValidIBANNeedsBothChecks(t *testing.T) {
	for _, iban := range []string{
		shortIBANPassingMod97,
		longIBANPassingMod97,
		foreignIBANPassingMod97,
	} {
		if !ibanChecksumOK(iban) {
			t.Fatalf("test setup is wrong: %q should satisfy mod-97", iban)
		}
		if IsValidIBAN(iban) {
			t.Errorf("IsValidIBAN(%q) = true, want false: mod-97 passes but the structure is wrong", iban)
		}
	}
}
